### ISSUE TITLE
PropType error when using React 16

### ISSUE THREAD

**Issue by yuchuan1** [markau/react-svg-timer#2]
TypeError: _react2.default.PropTypes is undefined
(anonymous function)
node_modules/react-svg-timer/lib/TimerSVG.js:49

  46 | };
  47 | 
  48 | TimerSVG.propTypes = {
> 49 |   outerColor: _react2["default"].PropTypes.string,
  50 |   innerColor: _react2["default"].PropTypes.string,
  51 |   countdownColor: _react2["default"].PropTypes.string,
  52 |   displayCountdown: _react2["default"].PropTypes.bool,

**Comment by markau** [comment]
Thanks for reporting the issue. This project is more out of date than I realised. I will look into it. Thanks again.

**Comment by markau** [comment]
hey @yuchuan1 I have uplifted this project and published a new version to npm. Confirmed working with Create React App (ES and TS). Thanks for letting me know!
