### ISSUE TITLE
Add a way to start the timer programatically

### ISSUE THREAD

**Issue by vedransisic** [markau/react-svg-timer#3]
This package is great, and works really well, but there is no way to programmatically start the timer. 
You should definitely add this as a feature.

**Comment by TonsOfFun** [comment]
I was looking to do the same thing. You can reference the timer in the parent and call `start()`,  `pause()`, and `reset()`

```  
  class Parent extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      resetRequested: false,
      timerIsComplete: false,
      logMilliseconds: true
    };

    this.timer = React.createRef();
    
    componentDidMount(){
        this.timer.current.toggleStart()
    }
    
    render() {
       return (
          <ReactSvgTimer
            ref={this.timer} />
       )
    }
```
https://stackoverflow.com/questions/37949981/call-child-method-from-parent
